### ISSUE TITLE
"TypeError: Cannot read property 'match' of null" on both the cloudant nodes

### ISSUE THREAD

**Issue by threecubet** [IBM/email-support-classifier#3]
![node-red](https://user-images.githubusercontent.com/43717422/62756256-af456e80-ba94-11e9-9ae1-4750931dad73.png)

When i send an email the node reads the payload and execute the function but when the payload and from address is passed to the cloudant node i get a response like  

`TypeError: Cannot read property 'match' of null`

**Comment by muralidharchavan** [comment]
Can you double click the "AddFromEMailToPayload" node and provide the contents pls?

**Comment by threecubet** [comment]
`msg.temppayload = msg.payload
msg.payload = msg.header.from.value[0].address
return msg;`
this is what the content is

**Comment by muralidharchavan** [comment]
Looks like msg.header.from.value[0].address is null. Please confirm what is the value of msg.header.from.value[0].address.

**Comment by threecubet** [comment]
In the above image.
In the debug tab the second object description shows the response from the function

`from: object
value: array[1]
0: object
address: "akhil.raj@cubettech.com"`

**Comment by muralidharchavan** [comment]
Is the cloudant database, customer_data,  populated with the email id "akhil.raj@gmail.com" as _id?

**Comment by threecubet** [comment]
yes it is

**Comment by threecubet** [comment]
I get this error whenever i deploy the flow even before sending an email.

**Comment by muralidharchavan** [comment]
Ok. What happens if you ignore the error and then send an email. Do you still get that error?

**Comment by threecubet** [comment]
ya it wont work, shows up with the same issue

**Comment by muralidharchavan** [comment]
Ok, just to eliminate Cloudant database issue, can I suggest you to inject your own text, instead of email, and then check if data is getting updated in Cloudant DB? Let's narrow down if Cloudant is causing the issue here.

**Comment by muralidharchavan** [comment]
Hi. Were you able to resolve this issue? An alternate option to fix this issue is to use cloudant database that was created as part of node-red service.
