### ISSUE TITLE
TypeError: Cannot read property 'match' of null when deploy cloudant 

### ISSUE THREAD

**Issue by vinhyenvodoi98** [IBM/email-support-classifier#6]
![image](https://user-images.githubusercontent.com/33363513/100095379-f6739080-2e8c-11eb-89b8-8f7cdbc0a7f4.png)
i try to insert text to cloudant but have this error , i was correctly setting 
![image](https://user-images.githubusercontent.com/33363513/100095506-2b7fe300-2e8d-11eb-949c-6a0e75311113.png)
but can't insert data to cloudant

**Comment by muralidharchavan** [comment]
Hi. Seems there is some issue with connecting to cloudant using the cloudant node configured as an external cloudant database. You may use the cloudant database that gets created as part of node-red service creation. For this, double click on cloudant nodes in your node-red flow, and under service dropdown, select the cloudant database that was created as part of node-red instead of "external cloudant or couch service". Deploy the flow and it should work fine now.

**Comment by vinhyenvodoi98** [comment]
@muralidharchavan  thank for reply 
![image](https://user-images.githubusercontent.com/33363513/100119302-495b4100-2ea9-11eb-8bdb-66dede2e99fa.png)
but as you see there are no other option in when i click to service dropdown

**Comment by muralidharchavan** [comment]
I just now created a Node-RED service instance (lite version) and by default, it created a Cloudant database service. I could refer to that service instance. When was the node-RED service instance created? Is it possible for you to create another instance (or maybe delete the existing one and create a new one)?

![image](https://user-images.githubusercontent.com/25784779/100229715-af4bd500-2f4a-11eb-8a99-d33299b87e40.png)

Image to show Cloudant instance getting created along with Node-RED
![image](https://user-images.githubusercontent.com/25784779/100229967-09e53100-2f4b-11eb-9da9-0cf95b3cff84.png)

**Comment by vinhyenvodoi98** [comment]
@muralidharchavan 
i just created node-red 
![image](https://user-images.githubusercontent.com/33363513/100242191-19727300-2f67-11eb-93e4-642a5300d99f.png)
and there are no other option
![image](https://user-images.githubusercontent.com/33363513/100242406-52124c80-2f67-11eb-852e-3ee36412d1a6.png)
But i found this when run `yarn start`
![image](https://user-images.githubusercontent.com/33363513/100242272-3444e780-2f67-11eb-8335-50e81e75eb8d.png)

**Comment by vinhyenvodoi98** [comment]
@muralidharchavan 
i try to create a new cloudant service in another account and try to connect to node-red . and it not working 
i using node v12.16.2 in ubuntu 16.04

**Comment by muralidharchavan** [comment]
Are you available for a meeting, on Monday, so you can share your screen. Let me see if I can find out what is the issue.

**Comment by vinhyenvodoi98** [comment]
@muralidharchavan yes , what time you available on monday ?

**Comment by muralidharchavan** [comment]
Will 4:30 PM (IST) / 11 AM (UTC) work for you?

**Comment by vinhyenvodoi98** [comment]
@muralidharchavan yes , could you send me google meet or zoom link ?

**Comment by muralidharchavan** [comment]
https://ibm.webex.com/meet/muralidhar.chavan - hope Webex is fine.

**Comment by vinhyenvodoi98** [comment]
@muralidharchavan it fine ! could we start now

**Comment by muralidharchavan** [comment]
Possible to join this link pls.. some issues with zoom as well.. 
meet.google.com/weu-iabn-zxp

**Comment by vinhyenvodoi98** [comment]
@muralidharchavan 
![image](https://user-images.githubusercontent.com/33363513/100600079-65406600-3333-11eb-9190-de49b3597a42.png)
it works !

**Comment by muralidharchavan** [comment]
Cool.. Glad that it works and the screen-sharing session helped.
